### ISSUE TITLE
Additional 

### ISSUE THREAD

**Issue by Sugarberrys** [ChatDisabled/nativeAudio#5]
Hey, so i tried your weaponaddon, it works fine default, soon as I replace 
[x16pistol_sounds.dat54.rel](https://github.com/ChatDisabled/nativeAudio/blob/master/weaponAudio/x16pistol/x16pistol_sounds.dat54.rel)
and 
[x16pistol_game.dat151.rel](https://github.com/ChatDisabled/nativeAudio/blob/master/weaponAudio/x16pistol/x16pistol_game.dat151.rel)
the audio bugs out and it seems like the audio is at far and at its lowest point. can you help me out?

**Comment by ChatDisabled** [comment]
I don't really want to help further because it is simply to difficult to explain let alone people actually understanding it. All I can say is play around with it and research it further yourself
